export const FULFILLED= "_FULFILLED";
export const PENDING="_PENDING";

export const GET_POSTS="GET_POSTS";
export const GET_EVENTS="GET_EVENTS";
export const ADD_SUBSCRIBER="ADD_SUBSCRIBER";
export const GET_SUBSCRIBERS="GET_SUBSCRIBERS";
export const REMOVE_SUBSCRIBER="REMOVE_SUBSCRIBER";