CREATE TABLE events(
Date DATE,
PostDate TIMESTAMP,
StartTime VARCHAR,
EndTime VARCHAR,
City TEXT,
State TEXT,
Zipcode INT,
Address TEXT,
Title VARCHAR,
Description TEXT,
ImageRef VARCHAR,
VolunteerInfo VARCHAR,
DonorInfo VARCHAR,
EventID SERIAL PRIMARY KEY,
latitude int,
longitude int,
catalogue text,
host text
);
