export default {
    someData: "Yeah Tiny Rick!",
    posts:null,
    events:null,
    userPosts:null,
    userEvents:null,
    subscriberEmail:null,
    emailList:null,
    eventDetail:null,
    postDetail:null,
    postPage:0,
    eventPage:0,
    blogPageSize:18,
    eventPageSize:6,
    user:null,
    redirect:'',
    comments:[],
    adminNotifications:null,
    adminUsers:null,
    adminPosts:null
}